site_name: bareASGI-rest
site_description: REST support for bareASGI
site_dir: docs

docs_dir: documentation

repo_name: rob-blackbourn/bareASGI-rest
repo_url: https://github.com/rob-blackbourn/bareASGI-rest
edit_uri: ""

theme:
    name: 'material'

nav:
  - index.md
  - User Guide:
    - user-guide/installation.md
    - user-guide/usage.md
  - API:
    - bareasgi_rest: api/bareasgi_rest.md
  
markdown_extensions:
  - admonition
  - codehilite
  - jetblack_markdown.autodoc:
      class_from_init: true
      ignore_dunder: true
      ignore_private: true
      ignore_all: false
      ignore_inherited: false
      prefer_docstring: true
      template_folder: templates

extra_css:
    - css/custom.css
