site_name: bareASGI-rest
site_description: REST support for bareASGI

repo_name: rob-blackbourn/bareASGI-rest
repo_url: https://github.com/rob-blackbourn/bareASGI-rest
edit_uri: ""

theme:
  name: "material"

nav:
  - index.md
  - User Guide:
      - user-guide/installation.md
      - user-guide/getting-started.md
  - API:
      - bareasgi_rest: api/bareasgi_rest.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - jetblack_markdown.autodoc:
      class_from_init: true
      ignore_dunder: true
      ignore_private: true
      ignore_all: false
      ignore_inherited: false
      follow_module_tree: false
      prefer_docstring: true
  - toc:
      permalink: true

extra_css:
  - css/custom.css

extra:
  version:
    provider: mike
    default: stable

plugins:
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
