[project]
name = "bareASGI-rest"
version = "5.0.0-alpha.2"
description = "REST support for bareASGI"
authors = [
    { name = "Rob Blackbourn", email = "rob.blackbourn@gmail.com" }
]
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: WWW/HTTP",
]
readme = "README.md"
dependencies = [
    "bareASGI >=5.0.0-alpha.4",
    "bareASGI-jinja2>=5.0.0-alpha.2",
    "docstring-parser>=0.15",
    "lxml>=5.4",
    "stringcase>=1.2",
    "jetblack-serialization>=4.0.0-alpha.4",
    "typing-extensions>=4",
    "typing_inspect>=0.9",
    "setuptools>=80.9<81"
]
license = "Apache-2.0"
license-files = [
    "LICENSE"
]
keywords = [
    "asgi",
    "web",
    "framework",
    "asyncio",
    "http",
]

[project.optional-dependencies]
dev = [
    "autopep8",
    "coverage",
    "mypy",
    "pytest",
    "pytest-asyncio",
    "pylint",
    "types-setuptools",
]
docs = [
    "mkdocs",
    "mkdocs-material",
    "jetblack-markdown",
    "mike",
]
examples = [
    "hypercorn",
    "uvicorn"
]

[project.urls]
Homepage = "https://rob-blackbourn.github.io/bareASGI-rest"
Repository = "https://github.com/rob-blackbourn/bareASGI-rest"
Issues = "https://github.com/rob-blackbourn/bareASGI-rest/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# pylint
[tool.pylint.main]
py-version = "3.12"
jobs = 4

[tool.pylint.basic]
good-names = ["i", "j", "k", "ex", "Run", "_"]
bad-names = ["foo", "bar", "baz", "toto", "tutu", "tata"]

[tool.pylint."messages control"]
disable = [
    "raw-checker-failed",
    "bad-inline-option",
    "locally-disabled",
    "file-ignored",
    "suppressed-message",
    "useless-suppression",
    "deprecated-pragma",
    "use-symbolic-message-instead",
    "use-implicit-booleaness-not-comparison-to-string",
    "use-implicit-booleaness-not-comparison-to-zero",
    "missing-module-docstring",
]

# pytest
[tool.pytest.ini_options]
testpaths = [
    "tests",
]
asyncio_default_fixture_loop_scope = "session"
asyncio_default_test_loop_scope = "function"

# mypy
[tool.mypy]
files = [ "src/bareasgi_rest", "tests", "demos" ]

[[tool.mypy.overrides]]
module = "pytest"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "stringcase"
ignore_missing_imports = true
